### ISSUE TITLE
Add a timeout for Bastion requests

### ISSUE THREAD

**Issue by KPull** [KPull/Bastion#14]
We should add support for a configurable timeout for separate Bastion requests. Each request will have a timeout. If the timeout elapses but the remote server (ie. the system under test) has not replied yet then Bastion considers the test as failed.

Once https://github.com/KPull/Bastion/issues/12 is done, this timeout can also be configured globally for all Bastion requests.

**Comment by benjie332** [comment]
I'll try this out, though I'd need a review to make sure that the configuration is in line with what is 'standard' !

**Comment by KPull** [comment]
@FrelliBB has an open pull request for Bastion global configuration which you might want to check out: https://github.com/KPull/Bastion/pull/28

**Comment by KPull** [comment]
Implemented in #47 by @benjie332.
