### ISSUE TITLE
Make a new request() method which doesn't take descriptive text

### ISSUE THREAD

**Issue by KPull** [KPull/Bastion#34]
At the moment, `Bastion.request()` requires descriptive text. It would be good to have an alternative `Bastion.request()` method which does not require descriptive text (the descriptive text is auto-generated somehow).

**Comment by ericathedev** [comment]
Working on this 😸 . Does anyone have an opinion on what the "default" text should be?

**Comment by ericathedev** [comment]
The only current read usage for `message` is in `BastionBuilderImpl#getDescriptiveText`which has no usages. Is that correct?

**Comment by KPull** [comment]
Hi @ericathedev! Welcome to Bastion. The name associated with the `HttpRequest` is meant to describe the request type (eg. 'Register a User'). The descriptive text with the Bastion test builder is meant to add additional info about the specific test (eg. 'Invalid Registration').

These two should appear in test reports but I noticed (as you said) that `BastionRunner` is not using the text inside the Bastion test builder.

**Comment by ericathedev** [comment]
@KPull shall we open the usage (or lack of) in a separate ticket? 

Otherwise for the `Bastion.request` would a default of empty string do?

**Comment by KPull** [comment]
Yep, want to open the issue yourself?

For `Bastion.request()` an empty string would be fine, yes.

**Comment by ericathedev** [comment]
Updated pull request and filed issue KPull/Bastion#50 🎆

**Comment by KPull** [comment]
Merged in #48.
