### ISSUE TITLE
Implement ignoreOrderForArrayProperties for JSON Assertions

### ISSUE THREAD

**Issue by tyrone-grech** [KPull/Bastion#40]
Implement the option to ignore the order of values in a JSON Assertion for particular array fields in case an API does not guarantee such ordering, while still reporting errors in case of missing or extra values in the array.

Examples:

`{ "array":["first","second","third"] }` == `{ "array":["third","first","second"] }`
`{ "array":["first","second","third"] }` != `{ "array":["third","first"] }`
`{ "array":["first","second","third"] }` != `{ "array":["third","first","second","fourth"] }`

**Comment by KPull** [comment]
Closing this issue. Thanks for your contribution.
